Repository POLZZAK/POLZZAK-Android, pull requests merged in 2023-10, with the labels that each got.

#143 [FEAT] 일러스트 적용
  app/src/main/java/com/polzzak_android/presentation/common/util/GlideUtil.kt
  app/src/main/java/com/polzzak_android/presentation/feature/auth/login/LoginFragment.kt
  app/src/main/java/com/polzzak_android/presentation/feature/auth/login/LoginViewModel.kt
  app/src/main/java/com/polzzak_android/presentation/feature/auth/login/model/LoginInfoModel.kt
  app/src/main/java/com/polzzak_android/presentation/feature/auth/signup/SignUpFragment.kt
  app/src/main/java/com/polzzak_android/presentation/feature/auth/signup/SignUpViewModel.kt
  app/src/main/java/com/polzzak_android/presentation/feature/auth/signup/model/MemberTypeModel.kt
  app/src/main/java/com/polzzak_android/presentation/feature/auth/signup/model/NickNameModel.kt
  app/src/main/java/com/polzzak_android/presentation/feature/auth/signup/model/ProfileImageModel.kt
  app/src/main/java/com/polzzak_android/presentation/feature/auth/signup/model/SignUpResultModel.kt
  app/src/main/java/com/polzzak_android/presentation/feature/link/management/base/BaseLinkManagementFragment.kt
  app/src/main/java/com/polzzak_android/presentation/feature/link/management/item/LinkManagementMainEmptyItem.kt
  app/src/main/java/com/polzzak_android/presentation/feature/link/search/kid/KidSearchOptionMenuFragment.kt
  app/src/main/java/com/polzzak_android/presentation/feature/link/search/protector/ProtectorSearchOptionMenuFragment.kt
  app/src/main/java/com/polzzak_android/presentation/feature/onboarding/item/OnBoardingPageItem.kt
  app/src/main/java/com/polzzak_android/presentation/feature/onboarding/kid/KidOnBoardingFragment.kt
  app/src/main/java/com/polzzak_android/presentation/feature/onboarding/model/OnBoardingPageModel.kt
  app/src/main/java/com/polzzak_android/presentation/feature/onboarding/protector/ProtectorOnBoardingFragment.kt
  app/src/main/res/drawable-nodpi/ic_login_logo.png
  app/src/main/res/drawable-nodpi/ic_onboarding_first.png
  app/src/main/res/drawable-nodpi/ic_onboarding_kid_fifth.png
  app/src/main/res/drawable-nodpi/ic_onboarding_kid_fourth.png
  app/src/main/res/drawable-nodpi/ic_onboarding_parent_fifth.png
  app/src/main/res/drawable-nodpi/ic_onboarding_parent_fourth.png
  app/src/main/res/drawable-nodpi/ic_onboarding_second.png
  app/src/main/res/drawable-nodpi/ic_onboarding_third.png
  app/src/main/res/drawable-nodpi/ic_search_option_menu_kid.png
  app/src/main/res/drawable-nodpi/ic_search_option_menu_parent.png
  app/src/main/res/drawable/ic_link_request_empty.xml
  app/src/main/res/drawable/ic_link_request_guide.xml
  app/src/main/res/drawable/ic_my_delete_account.xml
  app/src/main/res/drawable/ic_sign_up_kid_select_image.xml
  app/src/main/res/drawable/ic_sign_up_parent_select_image.xml
  app/src/main/res/drawable/ic_sign_up_select_kid.xml
  app/src/main/res/drawable/ic_sign_up_select_parent.xml
  app/src/main/res/drawable/img_login_logo.png
  app/src/main/res/drawable/shape_rectangle_gray_100_r12.xml
  app/src/main/res/layout/fragment_kid_notification.xml
  app/src/main/res/layout/fragment_login.xml
  app/src/main/res/layout/fragment_my_account_delete.xml
  app/src/main/res/layout/fragment_protector_notification.xml
  app/src/main/res/layout/fragment_search_option_menu.xml
  app/src/main/res/layout/item_link_management_main_empty.xml
  app/src/main/res/layout/item_link_request_empty.xml
  app/src/main/res/layout/item_link_request_guide.xml
  app/src/main/res/layout/item_link_request_loading.xml
  app/src/main/res/layout/item_on_boarding_page.xml
  app/src/main/res/layout/layout_signup_select_type.xml
  app/src/main/res/layout/layout_signup_set_nickname.xml
  app/src/main/res/navigation/protector_nav_graph.xml
Labels: feat, design

#144 프로필 이미지 표시, UI 작업
  app/src/main/java/com/polzzak_android/presentation/feature/coupon/detail/CouponDetailComponents.kt
  app/src/main/java/com/polzzak_android/presentation/feature/coupon/detail/CouponDetailScreen.kt
  app/src/main/java/com/polzzak_android/presentation/feature/coupon/detail/kid/KidCouponDetailFragment.kt
  app/src/main/java/com/polzzak_android/presentation/feature/coupon/main/content/CouponContentFragment.kt
  app/src/main/java/com/polzzak_android/presentation/feature/coupon/main/kid/KidCouponFragment.kt
  app/src/main/java/com/polzzak_android/presentation/feature/coupon/main/protector/ProtectorCouponFragment.kt
  app/src/main/java/com/polzzak_android/presentation/feature/myPage/point/history/PointHistoryFragment.kt
  app/src/main/java/com/polzzak_android/presentation/feature/myPage/point/ranking/kid/KidRankingFragment.kt
  app/src/main/java/com/polzzak_android/presentation/feature/myPage/point/ranking/protector/ProtectorRankingFragment.kt
  app/src/main/java/com/polzzak_android/presentation/feature/stamp/detail/kid/KidStampBoardDetailFragment.kt
  app/src/main/java/com/polzzak_android/presentation/feature/stamp/detail/screen/KidProtectorStampDetailScreen.kt
  app/src/main/java/com/polzzak_android/presentation/feature/stamp/detail/screen/ProtectorStampBoardDetailScreen.kt
  app/src/main/java/com/polzzak_android/presentation/feature/stamp/main/completed/ProtectorCompletedFragment.kt
  app/src/main/java/com/polzzak_android/presentation/feature/stamp/main/kid/KidMainFragment.kt
  app/src/main/java/com/polzzak_android/presentation/feature/stamp/main/progress/ProtectorProgressFragment.kt
  app/src/main/java/com/polzzak_android/presentation/feature/stamp/main/protector/ProtectorMainFragment.kt
  app/src/main/res/layout/fragment_completed.xml
  app/src/main/res/layout/fragment_coupon_content.xml
  app/src/main/res/layout/fragment_progress.xml
  app/src/main/res/values/strings.xml
Labels: feat, design

#153 도장판 상세 일러스트 적용
  app/src/main/.DS_Store
  app/src/main/java/com/polzzak_android/presentation/component/dialog/CommonDialogHelper.kt
  app/src/main/java/com/polzzak_android/presentation/component/dialog/CommonDialogModel.kt
  app/src/main/java/com/polzzak_android/presentation/feature/stamp/detail/kid/KidStampBoardDetailFragment.kt
  app/src/main/java/com/polzzak_android/presentation/feature/stamp/detail/protector/ProtectorStampBoardDetailFragment.kt
  app/src/main/java/com/polzzak_android/presentation/feature/stamp/detail/screen/StampBoardDetailComponents.kt
  app/src/main/java/com/polzzak_android/presentation/feature/stamp/model/StampIcon.kt
  app/src/main/java/com/polzzak_android/presentation/feature/stamp/model/StampModel.kt
  app/src/main/res/.DS_Store
  app/src/main/res/drawable-nodpi/img_receive_coupon_success.png
  app/src/main/res/drawable-nodpi/img_request_stamp_success.png
  app/src/main/res/layout/common_dialog_mission.xml
Labels: design

#154 [FIX] 쿠폰함 메뉴 선택시 crash 발생
  app/src/main/java/com/polzzak_android/data/remote/model/response/CouponListResponse.kt
  app/src/main/java/com/polzzak_android/presentation/common/adapter/MainCouponPagerAdapter.kt
Labels: critical

#156 [FIX] 아이용 마이페이지 화면 수정
  app/src/main/java/com/polzzak_android/presentation/feature/myPage/kid/KidMyPageFragment.kt
  app/src/main/res/layout/fragment_kid_my_page.xml
  app/src/main/res/values/strings.xml
Labels: normal

#158 [FEAT] 보호자 쿠폰 상세 Fragment 구현
  app/src/main/java/com/polzzak_android/presentation/feature/coupon/detail/protector/ProtectorCouponDetailFragment.kt
  app/src/main/java/com/polzzak_android/presentation/feature/coupon/main/content/CouponContentFragment.kt
  app/src/main/res/navigation/kid_nav_graph.xml
  app/src/main/res/navigation/protector_nav_graph.xml
Labels: feat

#163 [DESIGN] 도장판 상세-보상 이미지 적용
  app/src/main/java/com/polzzak_android/presentation/feature/stamp/detail/screen/StampBoardDetailComponents.kt
  app/src/main/res/drawable/ic_reward_coupon.xml
Labels: design
